# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/checklists", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Checklist. As you add validations to Checklist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Checklist.create! valid_attributes
      get checklists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      checklist = Checklist.create! valid_attributes
      get checklist_url(checklist)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_checklist_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      checklist = Checklist.create! valid_attributes
      get edit_checklist_url(checklist)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Checklist" do
        expect do
          post checklists_url, params: { checklist: valid_attributes }
        end.to change(Checklist, :count).by(1)
      end

      it "redirects to the created checklist" do
        post checklists_url, params: { checklist: valid_attributes }
        expect(response).to redirect_to(checklist_url(Checklist.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Checklist" do
        expect do
          post checklists_url, params: { checklist: invalid_attributes }
        end.to change(Checklist, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post checklists_url, params: { checklist: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested checklist" do
        checklist = Checklist.create! valid_attributes
        patch checklist_url(checklist), params: { checklist: new_attributes }
        checklist.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the checklist" do
        checklist = Checklist.create! valid_attributes
        patch checklist_url(checklist), params: { checklist: new_attributes }
        checklist.reload
        expect(response).to redirect_to(checklist_url(checklist))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        checklist = Checklist.create! valid_attributes
        patch checklist_url(checklist), params: { checklist: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested checklist" do
      checklist = Checklist.create! valid_attributes
      expect do
        delete checklist_url(checklist)
      end.to change(Checklist, :count).by(-1)
    end

    it "redirects to the checklists list" do
      checklist = Checklist.create! valid_attributes
      delete checklist_url(checklist)
      expect(response).to redirect_to(checklists_url)
    end
  end
end
