# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/observations", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Observation. As you add validations to Observation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Observation.create! valid_attributes
      get observations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      observation = Observation.create! valid_attributes
      get observation_url(observation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_observation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      observation = Observation.create! valid_attributes
      get edit_observation_url(observation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Observation" do
        expect do
          post observations_url, params: { observation: valid_attributes }
        end.to change(Observation, :count).by(1)
      end

      it "redirects to the created observation" do
        post observations_url, params: { observation: valid_attributes }
        expect(response).to redirect_to(observation_url(Observation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Observation" do
        expect do
          post observations_url, params: { observation: invalid_attributes }
        end.to change(Observation, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post observations_url, params: { observation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested observation" do
        observation = Observation.create! valid_attributes
        patch observation_url(observation), params: { observation: new_attributes }
        observation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the observation" do
        observation = Observation.create! valid_attributes
        patch observation_url(observation), params: { observation: new_attributes }
        observation.reload
        expect(response).to redirect_to(observation_url(observation))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        observation = Observation.create! valid_attributes
        patch observation_url(observation), params: { observation: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested observation" do
      observation = Observation.create! valid_attributes
      expect do
        delete observation_url(observation)
      end.to change(Observation, :count).by(-1)
    end

    it "redirects to the observations list" do
      observation = Observation.create! valid_attributes
      delete observation_url(observation)
      expect(response).to redirect_to(observations_url)
    end
  end
end
