# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/observers", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Observer. As you add validations to Observer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Observer.create! valid_attributes
      get observers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      observer = Observer.create! valid_attributes
      get observer_url(observer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_observer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      observer = Observer.create! valid_attributes
      get edit_observer_url(observer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Observer" do
        expect do
          post observers_url, params: { observer: valid_attributes }
        end.to change(Observer, :count).by(1)
      end

      it "redirects to the created observer" do
        post observers_url, params: { observer: valid_attributes }
        expect(response).to redirect_to(observer_url(Observer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Observer" do
        expect do
          post observers_url, params: { observer: invalid_attributes }
        end.to change(Observer, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post observers_url, params: { observer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested observer" do
        observer = Observer.create! valid_attributes
        patch observer_url(observer), params: { observer: new_attributes }
        observer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the observer" do
        observer = Observer.create! valid_attributes
        patch observer_url(observer), params: { observer: new_attributes }
        observer.reload
        expect(response).to redirect_to(observer_url(observer))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        observer = Observer.create! valid_attributes
        patch observer_url(observer), params: { observer: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested observer" do
      observer = Observer.create! valid_attributes
      expect do
        delete observer_url(observer)
      end.to change(Observer, :count).by(-1)
    end

    it "redirects to the observers list" do
      observer = Observer.create! valid_attributes
      delete observer_url(observer)
      expect(response).to redirect_to(observers_url)
    end
  end
end
