# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/taxons", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Taxon. As you add validations to Taxon, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Taxon.create! valid_attributes
      get taxons_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      taxon = Taxon.create! valid_attributes
      get taxon_url(taxon)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_taxon_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      taxon = Taxon.create! valid_attributes
      get edit_taxon_url(taxon)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Taxon" do
        expect do
          post taxons_url, params: { taxon: valid_attributes }
        end.to change(Taxon, :count).by(1)
      end

      it "redirects to the created taxon" do
        post taxons_url, params: { taxon: valid_attributes }
        expect(response).to redirect_to(taxon_url(Taxon.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Taxon" do
        expect do
          post taxons_url, params: { taxon: invalid_attributes }
        end.to change(Taxon, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post taxons_url, params: { taxon: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested taxon" do
        taxon = Taxon.create! valid_attributes
        patch taxon_url(taxon), params: { taxon: new_attributes }
        taxon.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the taxon" do
        taxon = Taxon.create! valid_attributes
        patch taxon_url(taxon), params: { taxon: new_attributes }
        taxon.reload
        expect(response).to redirect_to(taxon_url(taxon))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        taxon = Taxon.create! valid_attributes
        patch taxon_url(taxon), params: { taxon: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested taxon" do
      taxon = Taxon.create! valid_attributes
      expect do
        delete taxon_url(taxon)
      end.to change(Taxon, :count).by(-1)
    end

    it "redirects to the taxons list" do
      taxon = Taxon.create! valid_attributes
      delete taxon_url(taxon)
      expect(response).to redirect_to(taxons_url)
    end
  end
end
