production:
  :count_name: Vashon CBC
  :checklist_year_type: audubon_year
  :custom_rows:
    - Please provide data to your sector leader or the count compiler by \d+\/\d+\/\d+\.
  :custom_row_format:
    - [0, 1, 4]
    - [2, 3, 5]
  :ebird_taxon_mapping:
    Brant (Black): Brant
    Domestic goose sp. (Domestic type): Domestic goose sp.
    Domestic goose sp. (Domestic type) x Canada Goose (hybrid): Domestic goose sp. x Canada Goose
    Green-winged Teal (American): Green-winged Teal
    Greater/Lesser Scaup: scaup sp.
    Common/Barrow's Goldeneye: goldeneye sp.
    Common/Red-breasted Merganser: merganser sp.
    Rock Pigeon (Feral Pigeon): Rock Pigeon
    Mew Gull (American): Mew Gull
    Western x Glaucous-winged Gull (hybrid): Western x Glaucous-winged Gull
    Larus sp.: gull sp.
    Downy Woodpecker (Pacific): Downy Woodpecker
    Northern Flicker (Yellow-shafted x Red-shafted): Northern Flicker (intergrade)
    Steller's Jay (Coastal): Steller's Jay
    Purple Finch (Western): Purple Finch
    Fox Sparrow (Sooty): Fox Sparrow
    White-crowned Sparrow (pugetensis): White-crowned Sparrow
    Zonotrichia sp.: sparrow sp.
    Spotted Towhee (oregonus Group): Spotted Towhee
    new world sparrow sp.: sparrow sp.

development:
  :count_name: Vashon CBC
  :checklist_year_type: audubon_year
  :custom_rows:
    - Please provide data to your sector leader or the count compiler by \d+\/\d+\/\d+\.
  :custom_row_format:
    - [0, 1, 4]
    - [2, 3, 5]
  :ebird_taxon_mapping:
    Brant (Black): Brant
    Domestic goose sp. (Domestic type): Domestic goose sp.
    Domestic goose sp. (Domestic type) x Canada Goose (hybrid): Domestic goose sp. x Canada Goose
    Green-winged Teal (American): Green-winged Teal
    Greater/Lesser Scaup: scaup sp.
    Common/Barrow's Goldeneye: goldeneye sp.
    Common/Red-breasted Merganser: merganser sp.
    Rock Pigeon (Feral Pigeon): Rock Pigeon
    Mew Gull (American): Mew Gull
    Western x Glaucous-winged Gull (hybrid): Western x Glaucous-winged Gull
    Larus sp.: gull sp.
    Downy Woodpecker (Pacific): Downy Woodpecker
    Northern Flicker (Yellow-shafted x Red-shafted): Northern Flicker (intergrade)
    Steller's Jay (Coastal): Steller's Jay
    Purple Finch (Western): Purple Finch
    Fox Sparrow (Sooty): Fox Sparrow
    White-crowned Sparrow (pugetensis): White-crowned Sparrow
    Zonotrichia sp.: sparrow sp.
    Spotted Towhee (oregonus Group): Spotted Towhee
    new world sparrow sp.: sparrow sp.

test:
  :count_name: Vashon CBC
  :checklist_year_type: audubon_year
  :custom_rows:
    - Please provide data to your sector leader or the count compiler by \d+\/\d+\/\d+\.
  :custom_row_format:
    - [0, 1, 4]
    - [2, 3, 5]
  :ebird_taxon_mapping:
    Brant (Black): Brant
    Domestic goose sp. (Domestic type): Domestic goose sp.
    Domestic goose sp. (Domestic type) x Canada Goose (hybrid): Domestic goose sp. x Canada Goose
    Green-winged Teal (American): Green-winged Teal
    Greater/Lesser Scaup: scaup sp.
    Common/Barrow's Goldeneye: goldeneye sp.
    Common/Red-breasted Merganser: merganser sp.
    Rock Pigeon (Feral Pigeon): Rock Pigeon
    Mew Gull (American): Mew Gull
    Western x Glaucous-winged Gull (hybrid): Western x Glaucous-winged Gull
    Larus sp.: gull sp.
    Downy Woodpecker (Pacific): Downy Woodpecker
    Northern Flicker (Yellow-shafted x Red-shafted): Northern Flicker (intergrade)
    Steller's Jay (Coastal): Steller's Jay
    Purple Finch (Western): Purple Finch
    Fox Sparrow (Sooty): Fox Sparrow
    White-crowned Sparrow (pugetensis): White-crowned Sparrow
    Zonotrichia sp.: sparrow sp.
    Spotted Towhee (oregonus Group): Spotted Towhee
    new world sparrow sp.: sparrow sp.
