# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfea2cb818bb0cb167347dd3e52319cfbc21d2c968bd187d719458a97b7dc9fa4a7498b50a311e7771c92a31a71d56b9d092f56646c3fd783abdb238d319e120

test:
  secret_key_base: 9ac861da90d64c0bef858082129580752bd887e43a485ae0994db4225a8bc2418ead62bd86d7b18a4e9969b5b7b46641690db3dde8d9d822ec1828e3fa447dfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
